-- Seed General Education / PE / NSTP subjects (course = NULL, shared by all courses)
INSERT IGNORE INTO subjects (id, code, name, units, course, year_level, semester) VALUES
(UUID(), 'GE101', 'Purposive Communication', 3, NULL, 1, '1st'),
(UUID(), 'GE102', 'Mathematics in the Modern World', 3, NULL, 1, '1st'),
(UUID(), 'GE103', 'Understanding the Self', 3, NULL, 1, '1st'),
(UUID(), 'PE101', 'Physical Education 1 - Movement Enhancement', 2, NULL, 1, '1st'),
(UUID(), 'NSTP101', 'NSTP 1', 3, NULL, 1, '1st'),
(UUID(), 'GE104', 'Readings in Philippine History', 3, NULL, 1, '2nd'),
(UUID(), 'GE105', 'The Contemporary World', 3, NULL, 1, '2nd'),
(UUID(), 'GE106', 'Ethics', 3, NULL, 1, '2nd'),
(UUID(), 'PE102', 'Physical Education 2 - Fitness Exercises', 2, NULL, 1, '2nd'),
(UUID(), 'NSTP102', 'NSTP 2', 3, NULL, 1, '2nd'),
(UUID(), 'GE107', 'Science, Technology and Society', 3, NULL, 2, '1st'),
(UUID(), 'GE108', 'Art Appreciation', 3, NULL, 2, '1st'),
(UUID(), 'GE109', 'Life and Works of Rizal', 3, NULL, 2, '2nd'),
(UUID(), 'PE103', 'Physical Education 3 - Individual and Dual Sports', 2, NULL, 3, '1st'),
(UUID(), 'PE104', 'Physical Education 4 - Team Sports', 2, NULL, 4, '2nd');

-- BSIT subjects
INSERT IGNORE INTO subjects (id, code, name, units, course, year_level, semester) VALUES
(UUID(), 'IT101', 'Computing Fundamentals', 3, 'BSIT', 1, '1st'),
(UUID(), 'IT102', 'Introduction to Programming', 3, 'BSIT', 1, '1st'),
(UUID(), 'IT103', 'Computer Organization and Architecture', 3, 'BSIT', 1, '2nd'),
(UUID(), 'IT104', 'Object-Oriented Programming', 3, 'BSIT', 1, '2nd'),
(UUID(), 'IT105', 'Discrete Structures', 3, 'BSIT', 1, '2nd'),
(UUID(), 'IT201', 'Data Structures and Algorithms', 3, 'BSIT', 2, '1st'),
(UUID(), 'IT202', 'Database Management Systems 1', 3, 'BSIT', 2, '1st'),
(UUID(), 'IT203', 'Web Systems and Technologies 1', 3, 'BSIT', 2, '1st'),
(UUID(), 'IT204', 'Statistics and Probability for IT', 3, 'BSIT', 2, '1st'),
(UUID(), 'IT205', 'Database Management Systems 2', 3, 'BSIT', 2, '2nd'),
(UUID(), 'IT206', 'Web Systems and Technologies 2', 3, 'BSIT', 2, '2nd'),
(UUID(), 'IT207', 'Operating Systems', 3, 'BSIT', 2, '2nd'),
(UUID(), 'IT208', 'Information Management', 3, 'BSIT', 2, '2nd'),
(UUID(), 'IT301', 'Systems Analysis and Design', 3, 'BSIT', 3, '1st'),
(UUID(), 'IT302', 'Software Engineering 1', 3, 'BSIT', 3, '1st'),
(UUID(), 'IT303', 'Network Fundamentals', 3, 'BSIT', 3, '1st'),
(UUID(), 'IT304', 'Human-Computer Interaction', 3, 'BSIT', 3, '1st'),
(UUID(), 'IT305', 'Mobile Application Development 1', 3, 'BSIT', 3, '1st'),
(UUID(), 'IT306', 'Software Engineering 2', 3, 'BSIT', 3, '2nd'),
(UUID(), 'IT307', 'Network Administration', 3, 'BSIT', 3, '2nd'),
(UUID(), 'IT308', 'Information Assurance and Security', 3, 'BSIT', 3, '2nd'),
(UUID(), 'IT309', 'Mobile Application Development 2', 3, 'BSIT', 3, '2nd'),
(UUID(), 'IT310', 'IT Project Management', 3, 'BSIT', 3, '2nd'),
(UUID(), 'IT311', 'Practicum / On-the-Job Training', 6, 'BSIT', 3, 'summer'),
(UUID(), 'IT401', 'Capstone Project 1', 3, 'BSIT', 4, '1st'),
(UUID(), 'IT402', 'Emerging Technologies', 3, 'BSIT', 4, '1st'),
(UUID(), 'IT403', 'IT Governance and Compliance', 3, 'BSIT', 4, '1st'),
(UUID(), 'IT404', 'IT Elective 1', 3, 'BSIT', 4, '1st'),
(UUID(), 'IT405', 'Capstone Project 2', 3, 'BSIT', 4, '2nd'),
(UUID(), 'IT406', 'IT Elective 2', 3, 'BSIT', 4, '2nd'),
(UUID(), 'IT407', 'Professional Issues in IT and Society', 3, 'BSIT', 4, '2nd');

-- BSCS subjects
INSERT IGNORE INTO subjects (id, code, name, units, course, year_level, semester) VALUES
(UUID(), 'CS101', 'Introduction to Computing', 3, 'BSCS', 1, '1st'),
(UUID(), 'CS102', 'Programming 1', 3, 'BSCS', 1, '1st'),
(UUID(), 'CS103', 'Programming 2', 3, 'BSCS', 1, '2nd'),
(UUID(), 'CS104', 'Discrete Mathematics', 3, 'BSCS', 1, '2nd'),
(UUID(), 'CS105', 'Digital Logic Design', 3, 'BSCS', 1, '2nd'),
(UUID(), 'CS201', 'Data Structures', 3, 'BSCS', 2, '1st'),
(UUID(), 'CS202', 'Computer Organization', 3, 'BSCS', 2, '1st'),
(UUID(), 'CS203', 'Calculus 1 for Computing', 3, 'BSCS', 2, '1st'),
(UUID(), 'CS204', 'Algorithms and Complexity', 3, 'BSCS', 2, '1st'),
(UUID(), 'CS205', 'Calculus 2 for Computing', 3, 'BSCS', 2, '2nd'),
(UUID(), 'CS206', 'Operating Systems', 3, 'BSCS', 2, '2nd'),
(UUID(), 'CS207', 'Linear Algebra for Computing', 3, 'BSCS', 2, '2nd'),
(UUID(), 'CS208', 'Numerical Methods', 3, 'BSCS', 2, '2nd'),
(UUID(), 'CS301', 'Theory of Computation', 3, 'BSCS', 3, '1st'),
(UUID(), 'CS302', 'Programming Languages', 3, 'BSCS', 3, '1st'),
(UUID(), 'CS303', 'Database Systems', 3, 'BSCS', 3, '1st'),
(UUID(), 'CS304', 'Computer Networks', 3, 'BSCS', 3, '1st'),
(UUID(), 'CS305', 'Software Engineering', 3, 'BSCS', 3, '1st'),
(UUID(), 'CS306', 'Compiler Design', 3, 'BSCS', 3, '2nd'),
(UUID(), 'CS307', 'Artificial Intelligence', 3, 'BSCS', 3, '2nd'),
(UUID(), 'CS308', 'Computer Graphics', 3, 'BSCS', 3, '2nd'),
(UUID(), 'CS309', 'Information Security', 3, 'BSCS', 3, '2nd'),
(UUID(), 'CS310', 'Research Methods in CS', 3, 'BSCS', 3, '2nd'),
(UUID(), 'CS311', 'Practicum / On-the-Job Training', 6, 'BSCS', 3, 'summer'),
(UUID(), 'CS401', 'Machine Learning', 3, 'BSCS', 4, '1st'),
(UUID(), 'CS402', 'Capstone Project 1', 3, 'BSCS', 4, '1st'),
(UUID(), 'CS403', 'Parallel and Distributed Computing', 3, 'BSCS', 4, '1st'),
(UUID(), 'CS404', 'CS Elective 1', 3, 'BSCS', 4, '1st'),
(UUID(), 'CS405', 'Capstone Project 2', 3, 'BSCS', 4, '2nd'),
(UUID(), 'CS406', 'CS Elective 2', 3, 'BSCS', 4, '2nd'),
(UUID(), 'CS407', 'Professional and Ethical Issues in CS', 3, 'BSCS', 4, '2nd');

-- BSBA subjects
INSERT IGNORE INTO subjects (id, code, name, units, course, year_level, semester) VALUES
(UUID(), 'BA101', 'Principles of Management', 3, 'BSBA', 1, '1st'),
(UUID(), 'BA102', 'Business Mathematics', 3, 'BSBA', 1, '1st'),
(UUID(), 'BA103', 'Business Communication', 3, 'BSBA', 1, '2nd'),
(UUID(), 'BA104', 'Microeconomics', 3, 'BSBA', 1, '2nd'),
(UUID(), 'BA105', 'Introduction to Accounting', 3, 'BSBA', 1, '2nd'),
(UUID(), 'BA201', 'Financial Accounting 1', 3, 'BSBA', 2, '1st'),
(UUID(), 'BA202', 'Macroeconomics', 3, 'BSBA', 2, '1st'),
(UUID(), 'BA203', 'Business Law 1', 3, 'BSBA', 2, '1st'),
(UUID(), 'BA204', 'Business Statistics', 3, 'BSBA', 2, '1st'),
(UUID(), 'BA205', 'Financial Accounting 2', 3, 'BSBA', 2, '2nd'),
(UUID(), 'BA206', 'Marketing Management', 3, 'BSBA', 2, '2nd'),
(UUID(), 'BA207', 'Business Law 2', 3, 'BSBA', 2, '2nd'),
(UUID(), 'BA208', 'Cost Accounting', 3, 'BSBA', 2, '2nd'),
(UUID(), 'BA301', 'Management Accounting', 3, 'BSBA', 3, '1st'),
(UUID(), 'BA302', 'Human Resource Management', 3, 'BSBA', 3, '1st'),
(UUID(), 'BA303', 'Operations Management', 3, 'BSBA', 3, '1st'),
(UUID(), 'BA304', 'Financial Management', 3, 'BSBA', 3, '1st'),
(UUID(), 'BA305', 'Strategic Management', 3, 'BSBA', 3, '2nd'),
(UUID(), 'BA306', 'Entrepreneurship', 3, 'BSBA', 3, '2nd'),
(UUID(), 'BA307', 'Business Research Methods', 3, 'BSBA', 3, '2nd'),
(UUID(), 'BA308', 'Taxation', 3, 'BSBA', 3, '2nd'),
(UUID(), 'BA309', 'On-the-Job Training', 6, 'BSBA', 3, 'summer'),
(UUID(), 'BA401', 'International Business', 3, 'BSBA', 4, '1st'),
(UUID(), 'BA402', 'Corporate Governance', 3, 'BSBA', 4, '1st'),
(UUID(), 'BA403', 'BA Elective 1', 3, 'BSBA', 4, '1st'),
(UUID(), 'BA404', 'Feasibility Study', 3, 'BSBA', 4, '2nd'),
(UUID(), 'BA405', 'Business Policy', 3, 'BSBA', 4, '2nd'),
(UUID(), 'BA406', 'BA Elective 2', 3, 'BSBA', 4, '2nd');

-- BSEd subjects
INSERT IGNORE INTO subjects (id, code, name, units, course, year_level, semester) VALUES
(UUID(), 'ED101', 'Child and Adolescent Development', 3, 'BSEd', 1, '1st'),
(UUID(), 'ED102', 'Foundation of Education', 3, 'BSEd', 1, '1st'),
(UUID(), 'ED103', 'The Teaching Profession', 3, 'BSEd', 1, '2nd'),
(UUID(), 'ED104', 'Technology for Teaching and Learning 1', 3, 'BSEd', 1, '2nd'),
(UUID(), 'ED105', 'The Child and Adolescent Learner', 3, 'BSEd', 1, '2nd'),
(UUID(), 'ED201', 'Facilitating Learner-Centered Teaching', 3, 'BSEd', 2, '1st'),
(UUID(), 'ED202', 'Assessment in Learning 1', 3, 'BSEd', 2, '1st'),
(UUID(), 'ED203', 'Social Dimensions of Education', 3, 'BSEd', 2, '1st'),
(UUID(), 'ED204', 'Assessment in Learning 2', 3, 'BSEd', 2, '2nd'),
(UUID(), 'ED205', 'The Inclusive Classroom', 3, 'BSEd', 2, '2nd'),
(UUID(), 'ED206', 'Technology for Teaching and Learning 2', 3, 'BSEd', 2, '2nd'),
(UUID(), 'ED207', 'Curriculum Design', 3, 'BSEd', 2, '2nd'),
(UUID(), 'ED301', 'Principles and Strategies of Teaching', 3, 'BSEd', 3, '1st'),
(UUID(), 'ED302', 'Educational Technology', 3, 'BSEd', 3, '1st'),
(UUID(), 'ED303', 'Classroom Management', 3, 'BSEd', 3, '1st'),
(UUID(), 'ED304', 'Field Study 1', 1, 'BSEd', 3, '1st'),
(UUID(), 'ED305', 'Reading and Writing Across the Curriculum', 3, 'BSEd', 3, '1st'),
(UUID(), 'ED306', 'Multicultural Education', 3, 'BSEd', 3, '2nd'),
(UUID(), 'ED307', 'Research in Education', 3, 'BSEd', 3, '2nd'),
(UUID(), 'ED308', 'Field Study 2', 1, 'BSEd', 3, '2nd'),
(UUID(), 'ED309', 'Special Topics in Education', 3, 'BSEd', 3, '2nd'),
(UUID(), 'ED310', 'Seminar in Teaching', 3, 'BSEd', 3, '2nd'),
(UUID(), 'ED311', 'Practice Teaching', 6, 'BSEd', 3, 'summer'),
(UUID(), 'ED401', 'Internship 1 - Student Teaching', 6, 'BSEd', 4, '1st'),
(UUID(), 'ED402', 'Educational Leadership', 3, 'BSEd', 4, '1st'),
(UUID(), 'ED403', 'Internship 2 - Student Teaching', 6, 'BSEd', 4, '2nd'),
(UUID(), 'ED404', 'Trends and Issues in Education', 3, 'BSEd', 4, '2nd');

-- BSCRIM subjects
INSERT IGNORE INTO subjects (id, code, name, units, course, year_level, semester) VALUES
(UUID(), 'CRIM101', 'Introduction to Criminology', 3, 'BSCRIM', 1, '1st'),
(UUID(), 'CRIM102', 'Criminal Law 1', 3, 'BSCRIM', 1, '1st'),
(UUID(), 'CRIM103', 'Criminal Law 2', 3, 'BSCRIM', 1, '2nd'),
(UUID(), 'CRIM104', 'Introduction to Forensic Science', 3, 'BSCRIM', 1, '2nd'),
(UUID(), 'CRIM201', 'Criminal Sociology', 3, 'BSCRIM', 2, '1st'),
(UUID(), 'CRIM202', 'Police Organization and Administration', 3, 'BSCRIM', 2, '1st'),
(UUID(), 'CRIM203', 'Criminal Evidence', 3, 'BSCRIM', 2, '2nd'),
(UUID(), 'CRIM204', 'Criminalistics 1', 3, 'BSCRIM', 2, '2nd'),
(UUID(), 'CRIM301', 'Criminalistics 2', 3, 'BSCRIM', 3, '1st'),
(UUID(), 'CRIM302', 'Penology and Correctional Administration', 3, 'BSCRIM', 3, '1st'),
(UUID(), 'CRIM303', 'Criminal Investigation', 3, 'BSCRIM', 3, '2nd'),
(UUID(), 'CRIM304', 'Crime Prevention', 3, 'BSCRIM', 3, '2nd'),
(UUID(), 'CRIM305', 'Practicum', 6, 'BSCRIM', 3, 'summer'),
(UUID(), 'CRIM401', 'Traffic Management', 3, 'BSCRIM', 4, '1st'),
(UUID(), 'CRIM402', 'Research in Criminology', 3, 'BSCRIM', 4, '1st'),
(UUID(), 'CRIM403', 'Capstone Project in Criminology', 3, 'BSCRIM', 4, '2nd'),
(UUID(), 'CRIM404', 'Ethics for Criminology Professionals', 3, 'BSCRIM', 4, '2nd')
