-- Extended student registration fields
ALTER TABLE students
  ADD COLUMN IF NOT EXISTS name_extension VARCHAR(20) AFTER middle_name,
  ADD COLUMN IF NOT EXISTS major VARCHAR(100) AFTER course,
  ADD COLUMN IF NOT EXISTS birthplace TEXT AFTER birthdate,
  ADD COLUMN IF NOT EXISTS civil_status VARCHAR(20) DEFAULT 'single' AFTER gender,
  ADD COLUMN IF NOT EXISTS guardian_name VARCHAR(200) AFTER civil_status,
  ADD COLUMN IF NOT EXISTS guardian_contact VARCHAR(20) AFTER guardian_name,
  ADD COLUMN IF NOT EXISTS enrollment_type VARCHAR(30) AFTER guardian_contact,
  ADD COLUMN IF NOT EXISTS mother_name VARCHAR(200) AFTER enrollment_type,
  ADD COLUMN IF NOT EXISTS father_name VARCHAR(200) AFTER mother_name,
  -- Educational Background
  ADD COLUMN IF NOT EXISTS elementary_school VARCHAR(200) AFTER father_name,
  ADD COLUMN IF NOT EXISTS elementary_year VARCHAR(10) AFTER elementary_school,
  ADD COLUMN IF NOT EXISTS junior_high_school VARCHAR(200) AFTER elementary_year,
  ADD COLUMN IF NOT EXISTS junior_high_year VARCHAR(10) AFTER junior_high_school,
  ADD COLUMN IF NOT EXISTS senior_high_school VARCHAR(200) AFTER junior_high_year,
  ADD COLUMN IF NOT EXISTS strand VARCHAR(100) AFTER senior_high_school,
  ADD COLUMN IF NOT EXISTS senior_high_year VARCHAR(10) AFTER strand,
  ADD COLUMN IF NOT EXISTS school_last_attended VARCHAR(200) AFTER senior_high_year,
  ADD COLUMN IF NOT EXISTS school_last_attended_address TEXT AFTER school_last_attended,
  ADD COLUMN IF NOT EXISTS course_section_last_attended VARCHAR(100) AFTER school_last_attended_address,
  ADD COLUMN IF NOT EXISTS year_last_attended VARCHAR(10) AFTER course_section_last_attended,
  -- Additional Information
  ADD COLUMN IF NOT EXISTS disability_type VARCHAR(200) DEFAULT 'N/A' AFTER year_last_attended,
  ADD COLUMN IF NOT EXISTS disability_cause VARCHAR(200) DEFAULT 'N/A' AFTER disability_type,
  ADD COLUMN IF NOT EXISTS school_year VARCHAR(20) AFTER disability_cause,
  ADD COLUMN IF NOT EXISTS semester VARCHAR(20) AFTER school_year,
  ADD COLUMN IF NOT EXISTS employment_status VARCHAR(50) DEFAULT 'not_employed' AFTER semester,
  ADD COLUMN IF NOT EXISTS company_name VARCHAR(200) AFTER employment_status,
  ADD COLUMN IF NOT EXISTS company_location TEXT AFTER company_name,
  ADD COLUMN IF NOT EXISTS religion VARCHAR(100) AFTER company_location,
  ADD COLUMN IF NOT EXISTS als_info VARCHAR(200) AFTER religion,
  ADD COLUMN IF NOT EXISTS ip_info VARCHAR(200) AFTER als_info,
  ADD COLUMN IF NOT EXISTS is_solo_parent TINYINT(1) DEFAULT 0 AFTER ip_info,
  ADD COLUMN IF NOT EXISTS consent_given TINYINT(1) DEFAULT 0 AFTER is_solo_parent;
