-- Extended student registration fields
ALTER TABLE students
  ADD COLUMN name_extension VARCHAR(20) AFTER middle_name,
  ADD COLUMN major VARCHAR(100) AFTER course,
  ADD COLUMN birthplace TEXT AFTER birthdate,
  ADD COLUMN civil_status VARCHAR(20) DEFAULT 'single' AFTER gender,
  ADD COLUMN guardian_name VARCHAR(200) AFTER civil_status,
  ADD COLUMN guardian_contact VARCHAR(20) AFTER guardian_name,
  ADD COLUMN enrollment_type VARCHAR(30) AFTER guardian_contact,
  ADD COLUMN mother_name VARCHAR(200) AFTER enrollment_type,
  ADD COLUMN father_name VARCHAR(200) AFTER mother_name,
  ADD COLUMN elementary_school VARCHAR(200) AFTER father_name,
  ADD COLUMN elementary_year VARCHAR(10) AFTER elementary_school,
  ADD COLUMN junior_high_school VARCHAR(200) AFTER elementary_year,
  ADD COLUMN junior_high_year VARCHAR(10) AFTER junior_high_school,
  ADD COLUMN senior_high_school VARCHAR(200) AFTER junior_high_year,
  ADD COLUMN strand VARCHAR(100) AFTER senior_high_school,
  ADD COLUMN senior_high_year VARCHAR(10) AFTER strand,
  ADD COLUMN school_last_attended VARCHAR(200) AFTER senior_high_year,
  ADD COLUMN school_last_attended_address TEXT AFTER school_last_attended,
  ADD COLUMN course_section_last_attended VARCHAR(100) AFTER school_last_attended_address,
  ADD COLUMN year_last_attended VARCHAR(10) AFTER course_section_last_attended,
  ADD COLUMN disability_type VARCHAR(200) DEFAULT 'N/A' AFTER year_last_attended,
  ADD COLUMN disability_cause VARCHAR(200) DEFAULT 'N/A' AFTER disability_type,
  ADD COLUMN school_year VARCHAR(20) AFTER disability_cause,
  ADD COLUMN semester VARCHAR(20) AFTER school_year,
  ADD COLUMN employment_status VARCHAR(50) DEFAULT 'not_employed' AFTER semester,
  ADD COLUMN company_name VARCHAR(200) AFTER employment_status,
  ADD COLUMN company_location TEXT AFTER company_name,
  ADD COLUMN religion VARCHAR(100) AFTER company_location,
  ADD COLUMN als_info VARCHAR(200) AFTER religion,
  ADD COLUMN ip_info VARCHAR(200) AFTER als_info,
  ADD COLUMN is_solo_parent TINYINT(1) DEFAULT 0 AFTER ip_info,
  ADD COLUMN consent_given TINYINT(1) DEFAULT 0 AFTER is_solo_parent;
